name: Test Homebrew Formula

on:
  push:
    paths:
      - 'claude-tasker.rb'
      - 'HOMEBREW_INSTALL.md'
      - '.github/workflows/homebrew-test.yml'
  pull_request:
    paths:
      - 'claude-tasker.rb'
      - 'HOMEBREW_INSTALL.md'
      - '.github/workflows/homebrew-test.yml'

jobs:
  test-formula:
    name: Test Formula on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Cache Homebrew
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          ~/Library/Logs/Homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('claude-tasker.rb') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-
    
    - name: Install dependencies
      run: |
        # Install required tools (gh, jq, git are usually present)
        brew install gh jq
        
        # Python@3.11 will be installed as a dependency of our formula
    
    - name: Validate formula syntax
      run: |
        # Create a temporary tap for testing
        brew tap-new homebrew/test-tap
        cp ./claude-tasker.rb $(brew --repo homebrew/test-tap)/Formula/
        
        # Audit the formula in the tap
        brew audit --strict homebrew/test-tap/claude-tasker
    
    - name: Test formula installation
      run: |
        # Install from the temporary tap
        brew install --build-from-source --verbose homebrew/test-tap/claude-tasker
    
    - name: Test formula functionality
      run: |
        # Set test mode environment variable
        export CLAUDE_TASKER_TEST_MODE=1
        
        # Test basic commands (without requiring Claude CLI for CI)
        claude-tasker --help
        
        # Test Python imports work
        python3 -c "import sys; sys.path.insert(0, '$(brew --prefix homebrew/test-tap/claude-tasker)/libexec/lib/python3.11/site-packages'); from claude_tasker.cli import main; print('Import successful')"
    
    - name: Run Homebrew tests
      run: |
        brew test homebrew/test-tap/claude-tasker
    
    - name: Test formula uninstallation
      run: |
        brew uninstall homebrew/test-tap/claude-tasker
        
        # Verify cleanup
        ! command -v claude-tasker
    
    - name: Test reinstallation
      run: |
        # Test that it can be reinstalled cleanly
        brew install --build-from-source homebrew/test-tap/claude-tasker
        claude-tasker --help

  test-formula-head:
    name: Test HEAD Formula
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Install HEAD version
      run: |
        # Create a temporary tap for HEAD testing
        brew tap-new homebrew/head-test-tap
        cp ./claude-tasker.rb $(brew --repo homebrew/head-test-tap)/Formula/
        
        # Install HEAD version from tap
        brew install --HEAD --build-from-source homebrew/head-test-tap/claude-tasker
    
    - name: Test HEAD functionality
      run: |
        # Set test mode environment variable
        export CLAUDE_TASKER_TEST_MODE=1
        
        claude-tasker --help

  validate-documentation:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check documentation completeness
      run: |
        # Verify HOMEBREW_INSTALL.md exists and contains required sections
        grep -q "Installation Methods" HOMEBREW_INSTALL.md
        grep -q "Troubleshooting" HOMEBREW_INSTALL.md
        grep -q "Usage Examples" HOMEBREW_INSTALL.md
        
        # Check that formula file exists
        test -f claude-tasker.rb
        
        # Validate that documentation mentions correct command name
        grep -q "claude-tasker" HOMEBREW_INSTALL.md
    
    - name: Validate markdown syntax
      run: |
        # Install markdownlint-cli and validate
        npm install -g markdownlint-cli
        markdownlint HOMEBREW_INSTALL.md || echo 'Markdown validation completed with warnings'